### ISSUE TITLE
Users can have numbers, symbols and/or spaces in their name

### ISSUE THREAD

**Issue by Snow106** [overcooked/base#34]
![screenshot_20170511-144936](https://cloud.githubusercontent.com/assets/9102977/25973541/61a47b92-3659-11e7-80db-1cb924c28b28.png)
UPDATE:  symbols and blank spaces work too.
![screenshot_20170511-150658](https://cloud.githubusercontent.com/assets/9102977/25974041/aca0993a-365b-11e7-9ead-54ea1055f636.png)

**Comment by Justin-Leung** [comment]
Is this really a bug

**Comment by tehp** [comment]
Fixed.
