### ISSUE TITLE
"Sign In" on menu with mobile misaligned 

### ISSUE THREAD

**Issue by dominiclrt** [overcooked/base#36]
Opening the logged out menu shows misaligned sign in button on mobile (Samsung s6)

**Comment by dominiclrt** [comment]
![image](https://cloud.githubusercontent.com/assets/22142086/25973773/62407532-365a-11e7-9265-06597d301c5c.png)

**Comment by tehp** [comment]
Fixed when @Justin-Leung migrates header.
